name: ecoscore
description: Wanna save the earth?

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.0-dev.1
  adaptive_dialog: ^1.0.0
  cached_network_image: ^3.0.0
  copy_with_extension: ^2.0.0
  cupertino_icons: ^1.0.3
  dartx: ^0.7.1
  diffutil_dart: ^2.0.0+1
  easy_debounce: ^2.0.0
  flutter_svg: ^0.22.0
  gap: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  openfoodfacts:
    git:
      url: https://github.com/openfoodfacts/openfoodfacts-dart.git
      ref: db85933
  qr_code_scanner: ^0.5.1
  shimmer: ^2.0.0
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^2.0.3
  copy_with_extension_gen: ^2.0.1
  flutter_gen_runner: ^3.1.1
  hive_generator: ^1.1.0
  lint: ^1.5.3

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - colors/colors.xml

flutter:
  generate: true # for l10n
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
