name: ecoscore
description: Wanna save the earth?

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # misc
  riverpod: ^1.0.0-dev.7
  flutter_riverpod: ^1.0.0-dev.7
  copy_with_extension: ^2.0.0
  dartx: ^0.7.1
  diffutil_dart: ^2.0.0+1

  # DB
  hive: ^2.0.4
  hive_flutter: ^1.0.0

  # API
  openfoodfacts: ^1.2.0

  # UI
  shimmer: ^2.0.0
  gap: ^2.0.0
  intl: ^0.17.0
  flutter_svg: ^0.22.0
  easy_debounce: ^2.0.0
  cupertino_icons: ^1.0.3
  cached_network_image: ^3.0.0
  adaptive_dialog: ^1.0.0

  # camera
  camera: ^0.9.2+1
  native_device_orientation: ^1.0.0
  google_ml_vision:
    git:
      url: https://github.com/FredJul/flutter_google_ml_vision.git # my own version which only include barcode to reduce binary size
      ref: "3448e90"

  # system integration
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^2.0.3
  copy_with_extension_gen: ^2.0.1
  flutter_gen_runner: ^3.1.1
  hive_generator: ^1.1.0
  lint: ^1.7.2
  intl_utils: ^2.4.0

flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    inputs:
      - colors/colors.xml

flutter_intl:
  enabled: true
  class_name: Translation
  main_locale: en
  arb_dir: lib/translations
  output_dir: lib/translations/gen

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
